apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reactive-stream-writer-es
  labels:
    app: reactive-stream-writer-es
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reactive-stream-writer-es
  template:
    metadata:
      labels:
        app: reactive-stream-writer-es
    spec:
      containers:
      - name: reactive-stream-writer-es
        image: vgkowski/reactive-stream-writer:1.0
        imagePullPolicy: "Always"
        args: ["elasticsearch"]
        env:
        - name: "ES_HOST"
          value: "elasticsearch-vg-cluster.default.svc.cluster.local"
        - name: "ES_PORT"
          value: "9200"
        - name: "ES_PROTOCOL"
          value: "https"
        - name: "ES_TRUSTSTORE_PATH"
          value: "/elasticsearch/config/certs/truststore.jks"
        - name: "ES_TRUSTSTORE_PASSWORD"
          value: "changeit"
        - name: "ES_BULK_SIZE"
          value: "5000"
        - name: "THROUGHPUT"
          value: "10000"
        volumeMounts:
        - mountPath: /elasticsearch/config/certs
          name: client-vg-cluster
      volumes:
      - name: client-vg-cluster
        secret:
          defaultMode: 420
          secretName: es-certs-vg-cluster
