apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reactive-stream-writer-es
  labels:
    app: reactive-stream-writer-es
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactive-stream-writer-es
  template:
    metadata:
      labels:
        app: reactive-stream-writer-es
    spec:
      containers:
      - name: reactive-stream-writer-es
        image: vgkowski/reactive-stream-writer:1.0
        args: ["elasticsearch"]
        env:
        - name: "ES_HOST"
          value: "elasticsearch-vg-cluster.default.svc.cluster.local"
        - name: "ES_PORT"
          value: "9200"
          name: "ES_PROTOCOL"
          value: "https"
          name: "ES_KEYSTORE_PATH"
          value: "/elasticsearch/config/certs/node-keystore.jks"
        volumeMounts:
        - mountPath: /elasticsearch/config/certs
          name: es-certs-vg-cluster
      volumes:
      - name: es-certs-vg-cluster
        secret:
          defaultMode: 420
          secretName: es-certs-vg-cluster
